name: CI of mc_naoqi

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies (common)
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt-mirrors:
            mc-rtc:
              cloudsmith: mc-rtc/head
          apt: libboost-all-dev libgmock-dev libmc-rtc-dev
          pip: qibuild
        github: |
          - path: jrl-umi3218/pepper_description
            options: -DDISABLE_ROS=ON
          - path: jrl-umi3218/mc_pepper
          - path: arntanguy/libqi
            options: -DQI_WITH_TESTS=OFF
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
